最終課題２　商品詳細ページ実装
potepancamp/issei_miyauchi2 pull request #1
Opened 2021-07-22 04:33 UTC by isseimiyauchi

仕様
・商品詳細ページのテンプレート（potepan/sample/single_product.html.erb）を参考にして、商品詳細ページを実装
・商品のモデル名は Spree::Product
・ 実装するパス は /potepan/products 
・ルーティングの定義には適切に namespace を利用
・商品詳細ページにあって共通化すべき部分(ヘッダーなど)を共通化
・リンクの修正については、「トップページ」へのリンクのみ
・JS,cssは変更なし

テスト仕様
・商品詳細ページに期待する値が来ているか
・ヘルパーメソッド単体テスト
・requestテスト
・factorybot,caapybara導入

前回がgit,herokuあたりでエラーが出て、やり直しさせていただいております。前回の分でレビューいただきましたレビュアーの皆さん申し訳ありません。

2021-07-23 13:34 UTC, kaizumoto commented on config/application.rb
> +     end
14行目から20行目まで先頭に半角スペース1つ分多く入っていますので修正をお願いします。

2021-07-23 13:47 UTC, kaizumoto commented on app/views/potepan/products/show.html.erb
> +            <%= link_to "Home", potepan_path, id: "link_to_home3" %>
idを数値で取り扱っていますが、コード量が増えたり時間が経つと管理するのが大変になり保守性が低いです。
番号ではなく意味のある命名をするのが良いかと思います。

2021-07-23 13:49 UTC, kaizumoto commented
レビュアーの伊豆本です。
インラインでコメントしましたのでご確認ください。

2021-07-23 14:06 UTC, nakanoTaku commented on app/helpers/application_helper.rb
> +    base_title = "Potepan Store"
定数は大文字で書きましょう！

2021-07-23 14:11 UTC, nakanoTaku commented on config/storage.yml
> +  bucket: potepanec0987
`region`、`bucket`も環境変数から参照できるようにしましょう。

2021-07-23 14:12 UTC, nakanoTaku commented
レビュアーの中野です。
インラインでコメントしましたので、ご確認お願いします。

2021-07-23 14:15 UTC, isseimiyauchi commented on config/storage.yml
> +  bucket: potepanec0987
こちら課題１のやり方に沿って記述しましたので問題ないと思われるのですが。

2021-07-23 15:18 UTC, isseimiyauchi commented on config/storage.yml
> +  bucket: potepanec0987
環境変数設定しました。

2021-07-23 15:26 UTC, masanarih0ri commented on app/views/layouts/_header.html.erb
> +
細かいのですがHTMLの空行無くしましょう。

2021-07-23 15:28 UTC, masanarih0ri commented on spec/features/products_spec.rb
> +    end
その１、その３を残す意味がない気がするのですが、何か意図はありますか？

2021-07-23 15:29 UTC, masanarih0ri commented on spec/requests/potepan/products_controller_spec.rb
> +    scenario "assigns @product" do
日本語と英語が混ざっているので、どちらかに統一しましょう。

2021-07-24 01:59 UTC, bary822 reviewed
こんにちは。レビュアーの福井です。
いくつかコメントしました。ご確認ください。

インデントや改行に関する指摘が多いようですね。お使いのエディタにプラグイン等を導入することで機械的にこれらを検出・修正すると良いでしょう。

2021-07-24 01:59 UTC, bary822 commented on spec/features/products_spec.rb
> +require 'spree/testing_support/factories'
これは `rails_helper.rb`の中でやるようにしましょうか。
複数のテストファイルに渡って同じ記述が必要になりますので、まとめておいたほうが良いです。

2021-07-24 01:59 UTC, bary822 commented on spec/features/products_spec.rb
> +    end
こちらご対応いかがでしょうか? レビュアーから質問が来ているので最低限回答するようにしましょう。

2021-07-24 01:59 UTC, bary822 commented on spec/features/products_spec.rb
> +    scenario "display each product details" do
`scenario`に与える文言を英語か日本語で統一してください。

2021-07-24 01:59 UTC, bary822 commented on spec/requests/potepan/products_controller_spec.rb
> +RSpec.describe Potepan::ProductsController, type: :controller do
request specとcontroller specは全くの別物です。テストの内容を見る限りは後者だと思うので、ディレクトリ名も修正しておいてください。

2021-07-24 01:59 UTC, bary822 commented on spec/requests/potepan/products_controller_spec.rb
> +    scenario "assigns @product" do
こちらもご対応お願いします。

2021-07-24 02:11 UTC, isseimiyauchi commented on spec/features/products_spec.rb
> +require 'spree/testing_support/factories'
修正いたしました。

2021-07-24 02:11 UTC, isseimiyauchi commented on spec/features/products_spec.rb
> +    scenario "display each product details" do
はい、統一します。

2021-07-24 02:13 UTC, isseimiyauchi commented on spec/requests/potepan/products_controller_spec.rb
> +RSpec.describe Potepan::ProductsController, type: :controller do
controllerspecは非推奨と指摘され中途半端な修正になってしまいました。requestで統一しました。

2021-07-24 02:16 UTC, isseimiyauchi commented on spec/features/products_spec.rb
> +    end
その１、その２に変更しました。ご指摘の意味が分かりにくかったのですが、同じテストにしろとの指示でしたら違うレビュアー様に３つテストするようご指摘を受けているので申し訳ございません。テスト名のことでしたら対応させていただきました。

2021-07-24 02:16 UTC, isseimiyauchi commented on spec/requests/potepan/products_controller_spec.rb
> +    scenario "assigns @product" do
日本語で統一いたしました。

2021-07-24 02:37 UTC, isseimiyauchi commented
コメントいただいた修正点全て修正いたしました。
福井さんのアドバイスの通り、インデントの自動整形の設定をしたので、
次回からはインデントミスがないよう気をつけます。

2021-07-24 02:59 UTC, smatsumura-cq requested changes
レビュアーの松村です。
コメントしましたのでご確認をお願い致します。

あとrubocopによる不要な差分は元に戻してください。
差分ファイルが105もありますが、今回の課題であれば40前後には収まるはずです。

2021-07-24 02:59 UTC, smatsumura-cq commented on .rubocop.yml
> +inherit_from: .rubocop_todo.yml
この行とrubocop_todo.ymlを消してエラーが出ないようにrubocopの設定をしましょう。
今のままだと、rubocopのエラーを無視するという設定になっています。

2021-07-24 02:59 UTC, smatsumura-cq commented on Rakefile
> +
このようなrubocopの差分は今回のPRとは関係ないので元に戻しましょう。

2021-07-24 02:59 UTC, smatsumura-cq commented on spec/requests/potepan/products_request_spec.rb
> +    end
requestではrender_templateは非推奨なので削除して良いです。

2021-07-24 03:30 UTC, isseimiyauchi commented on .rubocop.yml
> +inherit_from: .rubocop_todo.yml
自動修正でエラーの数は減らしたのですが、このやり方は質問で回答してくださったレビュアーさんの勧めでやったものですから今からまた変更するのは少し抵抗があります。カリキュラム終了日が近づいているのもあるのですが、今までのレビューでそこまで重要視されていないところであるなら今回に限ってはこのままではダメでしょうか。上記の記述と自動修正でエラーは減らしました。

2021-07-24 03:30 UTC, isseimiyauchi commented on Rakefile
> +
修正いたしました。

2021-07-24 03:30 UTC, isseimiyauchi commented on spec/requests/potepan/products_request_spec.rb
> +    end
修正いたしました。

2021-07-24 05:50 UTC, isseimiyauchi commented
数点修正しましたが、rubocopはやはりこのままでいきます。
理由は、
１、エラーの出ているコードが私の作成したコードではないこと。
２、メンターの方に質問した際、エラーを無視する指示が出ていたこと

changefileが多くなり、見辛くなっているのは重々承知ですが、レビュアーの方々でも意見が分かれるところであれば、今回はこちらでいかせていただきたいです。

2021-07-24 10:32 UTC, return-nil approved these changes
LGTMです。
次からで良いのでコミットメッセージは再提出などではなく何を修正したのか分かるようにしたほうが良さそうです。

2021-07-24 12:39 UTC, merged